spring:
  profiles:
      active: uat

  security:
    filter:
      dispatcher-types: FORWARD,INCLUDE,REQUEST,ASYNC,ERROR

# 邮件配置
  mail:
    host: smtp.163.com
    username: m17601617806@163.com
    default-encoding: UTF-8
    password: Yl584521

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.vote.demo.model
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  config: classpath:log/logback-develop.xml

## Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=172.31.19.222
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=0